liste_index:
    path:     /
    defaults: { _controller: "ListerepasBundle:liste:index" }
    methods:  GET

liste_show:
    path:     /{id}/show
    defaults: { _controller: "ListerepasBundle:liste:show" }
    methods:  GET

liste_new:
    path:     /new
    defaults: { _controller: "ListerepasBundle:liste:new" }
    methods:  [GET, POST]

liste_edit:
    path:     /{id}/edit
    defaults: { _controller: "ListerepasBundle:liste:edit" }
    methods:  [GET, POST]

liste_delete:
    path:     /{id}/delete
    defaults: { _controller: "ListerepasBundle:liste:delete" }
    methods:  DELETE
