<?php

namespace ListerepasBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * listeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class listeRepository extends EntityRepository
{
}
