listerepas_liste:
    resource: "@ListerepasBundle/Resources/config/routing/liste.yml"
    prefix:   /liste

listerepas_homepage:
    path:     /
    defaults: { _controller: ListerepasBundle:Default:index }

# src/OC/PlatformBundle/Resources/config/routing.yml

hello_the_world:
    path:     /hello-world
    defaults: { _controller: OCPlatformBundle:Advert:index }

